name: My Workflow
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "awesomejinho"
        replace: "jkim2492"
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
